/// Flutter icons Home
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Home
///      fonts:
///       - asset: fonts/Home.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Home {
  Home._();

  static const _kFontFam = 'Home';
  static const String? _kFontPkg = null;

  static const IconData icon_metro_home_2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_ionic_ios_chatboxes_c = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_110 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
